//
// Document.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "OptiOfficeSDKAPI.Document")
public typealias Document = OptiOfficeSDKAPI.Document

extension OptiOfficeSDKAPI {

public struct Document: Codable, JSONEncodable, Hashable {

    public var id: String
    public var organizationId: String
    public var name: String
    public var url: String

    public init(id: String, organizationId: String, name: String, url: String) {
        self.id = id
        self.organizationId = organizationId
        self.name = name
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case organizationId
        case name
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(organizationId, forKey: .organizationId)
        try container.encode(name, forKey: .name)
        try container.encode(url, forKey: .url)
    }
}

}
