//
// Lead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "OptiOfficeSDKAPI.Lead")
public typealias Lead = OptiOfficeSDKAPI.Lead

extension OptiOfficeSDKAPI {

public struct Lead: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case new = "new"
        case inProgress = "in_progress"
        case closed = "closed"
    }
    public var id: String
    public var contactId: String
    public var channel: String
    public var status: Status

    public init(id: String, contactId: String, channel: String, status: Status) {
        self.id = id
        self.contactId = contactId
        self.channel = channel
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case contactId
        case channel
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(contactId, forKey: .contactId)
        try container.encode(channel, forKey: .channel)
        try container.encode(status, forKey: .status)
    }
}

}
