//
// Listing.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "OptiOfficeSDKAPI.Listing")
public typealias Listing = OptiOfficeSDKAPI.Listing

extension OptiOfficeSDKAPI {

public struct Listing: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case draft = "draft"
        case published = "published"
    }
    public var id: String
    public var officeId: String
    public var price: Double
    public var status: Status

    public init(id: String, officeId: String, price: Double, status: Status) {
        self.id = id
        self.officeId = officeId
        self.price = price
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case officeId
        case price
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(officeId, forKey: .officeId)
        try container.encode(price, forKey: .price)
        try container.encode(status, forKey: .status)
    }
}

}
