//
// Office.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "OptiOfficeSDKAPI.Office")
public typealias Office = OptiOfficeSDKAPI.Office

extension OptiOfficeSDKAPI {

public struct Office: Codable, JSONEncodable, Hashable {

    public var id: String
    public var organizationId: String
    public var title: String
    public var description: String?

    public init(id: String, organizationId: String, title: String, description: String? = nil) {
        self.id = id
        self.organizationId = organizationId
        self.title = title
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case organizationId
        case title
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(organizationId, forKey: .organizationId)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

}
