//
// OrganizationUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "OptiOfficeSDKAPI.OrganizationUpdate")
public typealias OrganizationUpdate = OptiOfficeSDKAPI.OrganizationUpdate

extension OptiOfficeSDKAPI {

public struct OrganizationUpdate: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 1, maxLength: 200, pattern: nil)
    static let descriptionRule = StringRule(minLength: nil, maxLength: 1000, pattern: nil)
    public var name: String?
    public var description: String?

    public init(name: String? = nil, description: String? = nil) {
        self.name = name
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

}
