//
// Payment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "OptiOfficeSDKAPI.Payment")
public typealias Payment = OptiOfficeSDKAPI.Payment

extension OptiOfficeSDKAPI {

public struct Payment: Codable, JSONEncodable, Hashable {

    public var id: String
    public var organizationId: String
    public var amount: Double
    public var currency: String
    public var description: String?

    public init(id: String, organizationId: String, amount: Double, currency: String, description: String? = nil) {
        self.id = id
        self.organizationId = organizationId
        self.amount = amount
        self.currency = currency
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case organizationId
        case amount
        case currency
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(organizationId, forKey: .organizationId)
        try container.encode(amount, forKey: .amount)
        try container.encode(currency, forKey: .currency)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

}
