//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "OptiOfficeSDKAPI.User")
public typealias User = OptiOfficeSDKAPI.User

extension OptiOfficeSDKAPI {

public struct User: Codable, JSONEncodable, Hashable {

    public var id: String
    public var email: String

    public init(id: String, email: String) {
        self.id = id
        self.email = email
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case email
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(email, forKey: .email)
    }
}

}
